create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
create table fizz_buzz (id bigint not null, limit_int integer, number1 integer, number2 integer, string1 varchar(255), string2 varchar(255), primary key (id)) engine=InnoDB;
create table fizzbuzz_statistic (id bigint not null, nb_ocurrence bigint, fizz_buzz_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table fizzbuzz_statistic add constraint FKa7m821tm1kmyxatcxx6n1am4f foreign key (fizz_buzz_id) references fizz_buzz (id);
