version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_DOCKER_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
  fizzbuzz:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create",
        "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
        "spring.jpa.properties.javax.persistence.schema-generation.scripts.action" : "create",
        "spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target" : "create.sql",
        "spring.jpa.properties.javax.persistence.schema-generation.scripts.create-source" : "metadata"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD


volumes:
  db:


